name: Deploy YOLOv8 to Existing App Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'real-time-detection'
  RESOURCE_GROUP: 'YOLOv8-Deploy-RG'
  PYTHON_VERSION: '3.11'  # Matches your linuxFxVersion
  WEBSITE_PORT: '8000'    # Standard FastAPI port

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglib2.0-0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn  # Required for production server

    - name: Package application
      run: |
        mkdir -p deployment_package
        # Copy only necessary files
        cp -r app/* deployment_package/
        cp requirements.txt deployment_package/
        # Include your model files (adjust path as needed)
        cp -r model/ deployment_package/model/
        cd deployment_package && zip -r ../app.zip .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./app.zip
